### ISSUE TITLE
Pin content

### ISSUE THREAD

**Issue by mastercyb** [Snedashkovsky/cyberdBot#12]
It would be nice if the bot pin somehow the content of cyberlinks, hence the content could be instantly available for display and search. Currently https://cyber.page do that, so if the cyberlink is done within the app, the content is nearly instantly available

**Comment by SaveTheAles** [comment]
@xhipster 
Nice one! 
I would love to advise https://pypi.org/project/ipfshttpclient/

**Comment by Snedashkovsky** [comment]
There is no need to repeat the https://cyber.page functionality.
