### ISSUE TITLE
Refactor with cyberpy

### ISSUE THREAD

**Issue by SaveTheAles** [Snedashkovsky/cyberdBot#22]
Want to offer you [cyberpy](https://pypi.org/project/cyberpy/) lib for wallet managing and transactions generating.

As result, you don't need your own node. You need just cyber endpoints for broadcasting transactions.

**Comment by Snedashkovsky** [comment]
@SaveTheAles thanks!
I implemented this library in other repositories.
I'll try to implement cyberpy here too!
