### ISSUE TITLE
Add 'link objects' feature

### ISSUE THREAD

**Issue by Snedashkovsky** [Snedashkovsky/cyberdBot#3]
Link of at least two objects
Supported object types:
- text
- photo
- files
- voice
- video
- url
- ipfs hash
- ipfs url
- cyberlink

**Comment by Antropocosmist** [comment]
Very good idea!

**Comment by Vgk88** [comment]
Good! Interesting functionality is the ability to collect cyberlinks with concrete hashtags automatically from the graph.

**Comment by Snedashkovsky** [comment]
Actions:
1. Press `Create cyberlink` button
2. Message from Bot `Please send the object from which the link comes`
3. Send object to Bot
4. Message from Bot `<Object type> successfully uploaded.
IPFS Hash: QmQBjGobG8Z2zLNahDseJJbsjbev2FVtr1jxkbsxAMRD2o
IPFS Link: https://ipfs.io/ipfs/QmQBjGobG8Z2zLNahDseJJbsjbev2FVtr1jxkbsxAMRD2o
Please send the object to which the link comes`
5. Send object to Bot
6. Message from Bot `<Object type> successfully uploaded.
IPFS Hash: QmQBjGobG8Z2zLNahDseJJbsjbev2FVtr1jxkbsxAMRD2o
IPFS Link: https://ipfs.io/ipfs/QmQBjGobG8Z2zLNahDseJJbsjbev2FVtr1jxkbsxAMRD2o`
7.  Message from Bot `cyberlink created: cyberlink*************`

**Comment by Snedashkovsky** [comment]
https://github.com/Snedashkovsky/cyberdBot/pull/9

**Comment by Snedashkovsky** [comment]
Done
