### ISSUE TITLE
Add menu item to report issues

### ISSUE THREAD

**Issue by maxim-uvarov** [Snedashkovsky/cyberdBot#30]
I suggest to add an Item "issues" in menu of bot that will bring user here: https://github.com/Snedashkovsky/cyberdBot/issues/

![image](https://user-images.githubusercontent.com/4896754/128975298-45335d26-0781-489b-a46e-03a4432c69ec.png)

![image](https://user-images.githubusercontent.com/4896754/128975311-4efb79df-88ad-4114-9f44-1cc3bd82604e.png)

![image](https://user-images.githubusercontent.com/4896754/128975322-569a4b5a-cec2-40b9-be98-ba450c90ee90.png)

**Comment by maxim-uvarov** [comment]
It can be made by botfather:
![image](https://user-images.githubusercontent.com/4896754/128985400-7c3f2478-5991-438e-895c-a5ba87c2acbe.png)

**Comment by Snedashkovsky** [comment]
Added commands
https://github.com/Snedashkovsky/cyberdBot/pull/33
