### ISSUE TITLE
Bot reported creation of cyberlink, but transaction failed

### ISSUE THREAD

**Issue by maxim-uvarov** [Snedashkovsky/cyberdBot#31]
I'm testing bot. I tried dialogue (as on screenshot). Bot reported that cyberlink was created. But when I clicked on link - cyber.page app says that transaction failed. https://rebyc.cyber.page/network/bostrom/tx/53047151B80356F671B607E0B01F519CDE2550463AACACA4C78B040FA41C6BC1
Ideally bot should say that transaction failed. 

![image](https://user-images.githubusercontent.com/4896754/128976018-f6a8d5fd-9d5b-44a6-80d5-755e32835250.png)

![image](https://user-images.githubusercontent.com/4896754/128976030-047f1037-b6bc-4e50-b00d-41ee30f352b0.png)

**Comment by Snedashkovsky** [comment]
Fixed https://github.com/Snedashkovsky/cyberdBot/pull/32
